stages:
  - build

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t my-app-t5:latest .
    - echo "GitLab successfully built the Docker image!"
